name: 'Tag Creation'
description: 'This action creates a new tag based on the commit message.'
branding:
  icon: 'tag'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/.github/workflows/tag.yml
      shell: bash
