name: Tag creation
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Get-Commit-Name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get commit name
        run: |
          COMMIT_NAME=$(git log -1 --pretty=format:'%s')
          echo $COMMIT_NAME
          echo "commit_name=$COMMIT_NAME" >> $GITHUB_ENV
      - name: Print GITHUB_ENV
        run: cat $GITHUB_ENV
